action_list:

  number_of_targets: 2

  action_0:
    action_type: pose    
    translation: [0.4, 0.2, 0.35]
    orientation: [-1.5, 0.0, 0.0]
    duration: 2.0
     
  action_1:
    action_type: pose    
    translation: [0.4, -0.4, 0.35]
    orientation: [-1.5, 0.0, 0.0]
    duration: 2.0